# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# ① 여기를 min_ios_version_supported 대신 직접 버전으로 지정
platform :ios, '15.1'

# ② Swift 프로젝트라면 use_frameworks! 을 켜 줍니다.
use_frameworks!

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  # (이 라인은 없어도 되지만, ENV로 다이나믹하게 제어하고 싶다면 남겨두세요)
  use_frameworks! :linkage => linkage.to_sym
end

use_frameworks! :linkage => :static

target 'Groo' do
  config = use_native_modules!


  # 순수 iOS SDK
  pod 'NMapsMap'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

